ModelBundle\Entity\ItemComment:

    properties:

        user:
            - NotBlank:
                message: "User is required."
                groups: [create, update]

        item:
            - NotBlank:
                message: "Item is required."
                groups: [create, update]

        content:
            - NotBlank:
                message: "Content is required."
                groups: [create, update]

        points:
            - NotBlank:
                message: "Points is required."
                groups: [create, update]

        ipv4:
            - NotBlank:
                message: "Ipv4 is required."
                groups: [create, update]

        creationdate:
            - NotBlank:
                message: "Creation date is required."
                groups: [create, update]
