ModelBundle\Entity\ItemVote:

    properties:

        user:
            - NotBlank:
                groups: [create, update]
                message: "User is required."

        item:
            - NotBlank:
                groups: [create, update]
                message: "Item is required."

        ipv4:
            - NotBlank:
                groups: [create, update]
                message: "Ipv4 is required."

        creationdate:
            - NotBlank:
                groups: [create, update]
                message: "Creation date is required."
