ModelBundle\Entity\ItemComment:

    properties:

        user:
            - NotBlank:
                groups: [create, update]
                message: "User is required."

        item:
            - NotBlank:
                groups: [create, update]
                message: "Item is required."

        content:
            - NotBlank:
                groups: [create, update]
                message: "Content is required."

        points:
            - NotBlank:
                groups: [create, update]
                message: "Points is required."

        ipv4:
            - NotBlank:
                groups: [create, update]
                message: "Ipv4 is required."

        creationdate:
            - NotBlank:
                groups: [create, update]
                message: "Creation date is required."
