ModelBundle\Entity\User:

    constraints:

        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
            errorPath: username
            message: 'This username is not available. Please choose another.'
            groups: [create, update]

    properties:

        username:

            - NotBlank:
                groups: [create, update]
                message: "Username is required."

            - Length:
                groups: [create, update]
                min: 2
                max: 15
                minMessage: 'Username must be at least {{ limit }} characters long.'
                maxMessage: 'Username cannot be longer than {{ limit }} characters.'

            - Regex:
                groups: [create, update]
                pattern: '/^[a-z0-9\-_]+$/'
                message: "Usernames can only contain lowercase letters, digits, dashes and underscores. Please choose another."

        plainpassword:

            - NotBlank:
                groups: [create]
                message: "Password is required."

            - Length:
                groups: [create]
                min: 8
                max: 4096
                minMessage: 'Password must be at least {{ limit }} characters long. Please choose another.'
                maxMessage: 'Password cannot be longer than {{ limit }} characters. Please choose another.'

        karma:
            - NotBlank:
                groups: [create, update]
                message: "Karma is required."

            - Range:
                groups: [create, update]
                min: 1
                minMessage: "Karma must be at least {{ limit }}."

        creationdate:
            - NotBlank:
                groups: [create, update]
                message: "Creation date is required."
